// Mirror of TDSuperApp.Data.Models.PermissionEnum.
// The backend serializes enums as strings (JsonStringEnumConverter), so these must match
// the C# names exactly.
export const Permission = {
  CanViewProducts: "CanViewProducts",
  CanEditProducts: "CanEditProducts",
  CanViewCarts: "CanViewCarts",
  CanAddToCart: "CanAddToCart",
  CanEditCart: "CanEditCart",
  CanClearCart: "CanClearCart",
  CanPlaceOrder: "CanPlaceOrder",
  CanViewOrders: "CanViewOrders",
  CanEditOrders: "CanEditOrders",
  CanViewBrands: "CanViewBrands",
  CanEditBrands: "CanEditBrands",
  CanViewDeliveryMethod: "CanViewDeliveryMethod",
  CanEditDeliveryMethod: "CanEditDeliveryMethod",
  CanSubmitEmailChangeRequest: "CanSubmitEmailChangeRequest",
  CanViewEmailChangeRequests: "CanViewEmailChangeRequests",
  CanEditEmailChangeRequests: "CanEditEmailChangeRequests",
  CanDeleteEmailChangeRequests: "CanDeleteEmailChangeRequests",
  CanViewEmailTemplates: "CanViewEmailTemplates",
  CanEditEmailTemplates: "CanEditEmailTemplates",
  CanViewWarehouses: "CanViewWarehouses",
  CanEditWarehouses: "CanEditWarehouses",
  CanViewPaymentMethods: "CanViewPaymentMethods",
  CanEditPaymentMethods: "CanEditPaymentMethods",
  CanAssignPermissions: "CanAssignPermissions",
  CanCreateRoles: "CanCreateRoles",
  CanEditRoles: "CanEditRoles",
  CanViewRoles: "CanViewRoles",
  CanViewPromos: "CanViewPromos",
  CanCreatePromos: "CanCreatePromos",
  CanEditPromos: "CanEditPromos",
  CanDeletePromos: "CanDeletePromos",
  CanChangeSettings: "CanChangeSettings",
  CanViewTransactions: "CanViewTransactions",
  CanCreateSubUser: "CanCreateSubUser",
  CanEditSubUser: "CanEditSubUser",
  CanViewSubUser: "CanViewSubUser",
  CanDeleteSubUser: "CanDeleteSubUser",
  CanCreateUser: "CanCreateUser",
  CanEditUser: "CanEditUser",
  CanDeleteUser: "CanDeleteUser",
  CanViewUser: "CanViewUser",
  CanCreateTicket: "CanCreateTicket",
  CanViewTicket: "CanViewTicket",
  CanEditTicket: "CanEditTicket",
  CanDeleteTicket: "CanDeleteTicket",
  CanEscalateTicket: "CanEscalateTicket",
  CanViewRatings: "CanViewRatings",
  CanViewRequestAppeals: "CanViewRequestAppeals",
  CanEditRequestAppeals: "CanEditRequestAppeals",
  CanCreateProductGroup: "CanCreateProductGroup",
  CanEditProductGroup: "CanEditProductGroup",
  CanViewProductGroup: "CanViewProductGroup",
  CanDeleteProductGroup: "CanDeleteProductGroup",
  CanViewDashboard: "CanViewDashboard",
  CanViewFeaturedProducts: "CanViewFeaturedProducts",
  CanEditFeaturedProducts: "CanEditFeaturedProducts",
} as const;

export type Permission = (typeof Permission)[keyof typeof Permission];
